"""Initial alembic revision

Revision ID: bf5b9a4cbd64
Revises: 
Create Date: 2016-04-06 15:36:03.887696

"""

# revision identifiers, used by Alembic.
revision = 'bf5b9a4cbd64'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expected_stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('warn_interval', sa.Integer(), nullable=True),
    sa.Column('fail_interval', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_designator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('deployed_stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_des_id', sa.Integer(), nullable=False),
    sa.Column('expected_stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expected_stream_id'], ['expected_stream.id'], ),
    sa.ForeignKeyConstraint(['ref_des_id'], ['reference_designator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('particle_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['deployed_stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('counts')
    op.drop_table('deployed_stream')
    op.drop_table('reference_designator')
    op.drop_table('expected_stream')
    ### end Alembic commands ###
